### ISSUE TITLE
App stuck in 'pending approvals'

### ISSUE THREAD

**Issue by ecamach13** [BIDMCDigitalPsychiatry/AppMapDB#109]
An app titled 'Back Pain Relief Yoga at Home' has been stuck in my pending approvals for quite some time, but I'm just getting around to asking about it. It was submitted on 12/3 but as much as I press 'approved' and refresh the page it won't leave my 'pending approvals' tab.

**Comment by cvanem** [comment]
@ecamach13 
This app rating looks like it had a previous rating which was never approved or archived.  See the screenshot (3rd row down).  I went ahead and marked it approved for you and it looks like the issue is resolved.  Let me know if you still have issues.

![image](https://user-images.githubusercontent.com/24579103/150024842-53762ed7-2e26-4560-a0d8-74d221951499.png)
