### ISSUE TITLE
Google SEO optimization

### ISSUE THREAD

**Issue by slagan1** [BIDMCDigitalPsychiatry/AppMapDB#82]
Although our site is indexed in Google, it does not appear in search results unless the exact URL (now `mindapps.org`) is searched. I'm not sure the root of the issue so wanted to ask about ways to improve SEO - is this something that we need to fix with google, or on the code side?

**Comment by cvanem** [comment]
@slagan1 

**Some background:** 
React applications consist mainly of Javascript code and the page content is loaded dynamically.  When a web crawler accesses the html page for this project, it basically sees a placeholder with limited HTML content.  In the past, web crawlers would only crawl HTML page content.  Google has since added the ability to crawl HTML + Javascript pages, where the html and Javascript code are loaded and the content is generated and indexed.

That being said, it is possible to do server side rendering and provide the web crawler with HTML only pages, but I would not recommend it for this project as it requires an additional server component and a hosting solution.  For the purposes of this project, the HTML + Javascript solution should work fine, but we may just need a few adjustments.    The only real draw-back with this method is it may take a little longer for the web crawler to pick up the changes (a few days to a week).  This will likely be a non-issue once the web page appears as desired as the general content shouldn't change that frequently.

Here are a few items I would start with:

1. Title - Possibly change the title to something more descriptive.  This is currently "BIDMC - Division of Digital Psychiatry".  This is visible to the user as the title of the page when searching.  It is also visible at the top of the browser when the user is on the page.

2. Description - Add a more descriptive description, which includes commonly used search terms and a human readable summary of the page.  This may be visible in the search engine as the summary of the page, but is not visible when the user is running the webpage.  The current description is: "BIDMC - Division of Digital Psychiatry".

3. Meta Tag Keywords - I can also add some hidden keywords if you can think of any common search terms.
4. Hidden Keywords - I can also add some hidden keywords to the main page content.

**Comment by jtorous** [comment]
Hi Chris,

I agree with your plan and simplicity is better (ie no new server
competent and hosting). We can wait days/weeks for the crawler


Title - Mobile Health Index and Navigation Database, App Evaluation
Resources frmo the Division of Digital Psychiatry at BIDMC

Description - MIND is an interactive database that helps anyone find mental
health and brain apps that meet the unique preference and needs for each
unique individual .Search apps across privacy, cost (including free),
evidence, engagement, and many other categories to learn which apps offer
the right combination of features for the right person at the right time.

Meta tags - mental health apps; therapy app, depression apps, free apps,
anxiety apps, stress apps, psych app, psychiatry apps
Hidden keywords - > same as meta tag keywords


Thanks,
John Torous

**Comment by cvanem** [comment]
@jtorous This has been completed.  I will give it a few days and re-visit once the crawler picks up the updates.

**Comment by cvanem** [comment]
The updates seem to have been picked up by the web crawler.   I tested some search keywords and had varying success:

mindapp database - Appears on 1st page
mobile health index database - Appears on 1st page
mind App Evaluation Resources - Appears 1st page
mental health app evaluation - Appears on 4th page
Division of Digital Psychiatry apps - Appears on 1st page

The search results appear acceptable and the overall search placement will improve over time as people search and click the link.

@jtorous Is this acceptable?  If so, the issue can be closed.

**Comment by jtorous** [comment]
Yes, This is great and will get us towards more visibility.

Thanks,
John
