### ISSUE TITLE
reposition images

### ISSUE THREAD

**Issue by ecamach13** [BIDMCDigitalPsychiatry/AppMapDB#94]
Can we make it so that we can reposition images/zoom in/zoom out of them for the cover photos on the news tab

**Comment by ecamach13** [comment]
<img width="1319" alt="Screen Shot 2021-06-09 at 11 36 24 AM" src="https://user-images.githubusercontent.com/70787908/121385345-062d6080-c917-11eb-8139-1c03a81c5896.png">

**Comment by cvanem** [comment]
This will require some custom implementation.  I will take a look and see if there are any existing libraries we can easily plug in that will accomplish this.

**Comment by cvanem** [comment]
@ecamach13 
I added the re-size and re-position to cover images when publishing content.  This should work for most everything you need, but there are some image size limitations related to in-browser image editing and storing in the database.  I have only found one image that exceeds the limits so far.  So for this image, you would need to manually edit it and re-upload.

We could alternatively switch the image store to use an S3 bucket instead of a database, which would eliminate the size limitation.  This would take a few more hours to implement, so please review and let me know if we need to do this or not.

**Comment by jtorous** [comment]
Let's keep the image size limits to keep it simpler.

-John

**Comment by cvanem** [comment]
Ok, will leave this as is and see how it works.
